version: '3.8'
services:
  python:
    container_name: python-django
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx-django
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - python
  postgres:
    image: postgres
    container_name: postgres-django
    restart: unless-stopped
    volumes:
      - "./postgres/backup:/tmp/"
      - "db:/var/lib/postgresql/data"
    env_file:
      - postgres/database.env # configure postgres
    ports:
      - "5432:5432"
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  db:
    driver: local